spring.application.name=unified-data-service
spring.config.additional-location=classpath:common.properties,classpath:i18n.properties,classpath:email.properties

# Actuator info
info.app.name=UNIFIED-DATA-SERVICE
info.app.description=This Microservice is used aggregating multiple ms data.
info.app.version=1.0.0
management.endpoint.health.show-details=always
management.endpoints.web.exposure.include=health

# NFS path
app.nfs.path=/tmp

# Server configuration
server.servlet.context-path=/ag
server.port=8083
server.tomcat.max-threads=200
server.tomcat.max-connections=1000
spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=20MB
spring.webflux.base-path=${server.servlet.context-path}

# DB config
spring.r2dbc.url=r2dbc:postgresql://localhost:5432/unifiedservice
#spring.r2dbc.username = postgres
#spring.r2dbc.password = Root@123

spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/unifiedservice

# Hibernate (JPA) properties
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.show_sql=true
spring.jpa.properties.hibernate.use_sql_comments=true
spring.jpa.properties.hibernate.format_sql=true

# Common-utils configuration properties
platform.database.url=${spring.datasource.url}
platform.database.username=${spring.datasource.username}
platform.database.password=${spring.datasource.password}
platform.database.driver-class-name=${spring.datasource.driver-class-name}
# these props make sure we make call to other Ms to load data
platform.api.reactive=true
platform.api.load.tenants=true
platform.api.load.users=true
platform.ms.tenant-manager=http://localhost:8081/tm
platform.ms.product-manager=http://localhost:8081/pm

#cloud-server config
spring.cloud.config.enabled=true
spring.cloud.config.uri=http://localhost:8181
spring.config.import=configserver:${spring.cloud.config.uri},classpath:common.properties,classpath:i18n.properties,classpath:email.properties
spring.cloud.config.username=internaluser
#spring.cloud.config.password=password123

# App Log config
logging.level.org.springframework=ERROR
logging.level.com.platform=INFO
logging.level.org.hibernate=ERROR
logging.level.org.hibernate.orm.jdbc.bind=ERROR
logging.level.org.hibernate.type=ERROR