# Config server
spring.application.name=cloud-config
server.port=8181
spring.cloud.bootstrap.enabled=true
spring.cloud.config.server.git.username=muhilkennedy
spring.cloud.config.server.git.password=<token>
spring.cloud.config.server.git.uri=https://github.com/muhilkennedy/cloud-config
spring.cloud.config.server.git.basedir=/tmp/${spring.application.name}
management.endpoints.web.exposure.include=health
#encrypt.key = <key>

#spring.cloud.config.server.git.force-pull

app.trusted.subnets=127.0.0.1

# Security config (client apps should authenticate with this creds)
spring.security.user.name=devUser
spring.security.user.password=devPassword